
steps:
- task: Npm@1
  displayName: 'Execute Test'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run test '

- script: 'npm i && npx playwright install'
  displayName: 'Install Playwright'

- task: PublishMultipleCucumberReport@1
  displayName: 'Publish Cucumber Report'
  inputs:
    jsonDir: 'test-results'
    outputPath: 'test-results/reports'
    theme: 'bootstrap'
    reportSuiteAsScenarios: true

