pool:
steps:
- task: Npm@1
  displayName: 'Execute Test'
  inputs:
    command: 'custom'
    verbose: false
    customCommand: 'run test'
  name: Azure Pipelines
  demands: npm

steps:
- script: 'npm i && npx playwright install'
  displayName: 'Install Playwright'

- task: Npm@1
  displayName: 'Execute Test'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run test '


