
steps:
- task: Npm@1
  displayName: 'Execute Test'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run test '

- script: 'npm i && npx playwright install'
  displayName: 'Install Playwright'



